name: find_your_best_teacher_today
description: A Flutter app to find your best teacher today.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lottie: ^3.1.2

  firebase_core: ^3.6.0
  