name: find_your_best_teacher_today
description: A Flutter app to find your best teacher today.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.13.5
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.4
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.4     
  emoji_picker_flutter: ^1.6.1
  flutter_sound: ^9.2.13+1
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  jitsi_meet_wrapper: ^0.1.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/         # Includes: teacher.png, student.png, app_logo.png,logo.png
    - assets/animations/      # For Lottie or other future animation files (includes teacher_logo_animation.json)
    - assets/images/default_avatar.png