import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class MessageBubble extends StatelessWidget {
  final String message;
    final bool isMe;
      final Timestamp timestamp;
        final String messageId;
          final String type; 
            final bool isTyping; 
              final VoidCallback uploadVoiceMessage; 

                const MessageBubble({
                    super.key,
                        required this.message,
                            required this.isMe,
                                required this.timestamp,
                                    required this.messageId,
                                        required this.type,
                                            required this.isTyping,
                                                required this.uploadVoiceMessage,
                                                  });

                                                    String _timeAgo(DateTime date) {
                                                        final now = DateTime.now();
                                                            final diff = now.difference(date);

                                                                if (diff.inSeconds < 60) return '${diff.inSeconds}s ago';
                                                                    if (diff.inMinutes < 60) return '${diff.inMinutes}m ago';
                                                                        if (diff.inHours < 24) return '${diff.inHours}h ago';
                                                                            return '${date.day}/${date.month}/${date.year}';
                                                                              }

                                                                                @override
                                                                                  Widget build(BuildContext context) {
                                                                                      return Align(
                                                                                            alignment: isMe ? Alignment.centerRight : Alignment.centerLeft,
                                                                                                  child: Column(
                                                                                                          crossAxisAlignment:
                                                                                                                      isMe ? CrossAxisAlignment.end : CrossAxisAlignment.start,
                                                                                                                              children: [
                                                                                                                                        // যদি অন্য কোনো ইউজার টাইপ করতে থাকে, তবে একটি ছোট্ট টাইপিং ইন্ডিকেটর দেখাবে
                                                                                                                                                  if (!isMe && isTyping)
                                                                                                                                                              Padding(
                                                                                                                                                                            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 2),
                                                                                                                                                                                          child: Text(
                                                                                                                                                                                                          'typing...',
                                                                                                                                                                                                                          style: TextStyle(
                                                                                                                                                                                                                                            fontSize: 12,
                                                                                                                                                                                                                                                              fontStyle: FontStyle.italic,
                                                                                                                                                                                                                                                                                color: Colors.grey[600],
                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                Container(
                                                                                                                                                                                                                                                                                                                                                            margin: const EdgeInsets.symmetric(vertical: 4, horizontal: 8),
                                                                                                                                                                                                                                                                                                                                                                        padding: const EdgeInsets.all(12),
                                                                                                                                                                                                                                                                                                                                                                                    decoration: BoxDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                  color: isMe ? Colors.blue[100] : Colors.grey[200],
                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: BorderRadius.circular(12),
                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                        child: Row(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      mainAxisSize: MainAxisSize.min,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (type == 'audio') ...[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const Icon(Icons.play_arrow, color: Color(0xFF128C7E)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(width: 8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width: 120,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  height: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      decoration: BoxDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: Colors.grey[400],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: BorderRadius.circular(5),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const SizedBox(width: 8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const Icon(Icons.mic, size: 16, color: Colors.grey),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ] else ...[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Flexible(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style: const TextStyle(fontSize: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: const EdgeInsets.only(left: 12, right: 12, bottom: 4),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _timeAgo(timestamp.toDate()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style: const TextStyle(fontSize: 10, color: Colors.grey),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                