import 'package:flutter/material.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import 'package:permission_handler/permission_handler.dart';

class LiveClassScreen extends StatefulWidget {
  final String channelName; 
    final String userName;

      const LiveClassScreen({
          super.key, 
              required this.channelName, 
                  required this.userName
                    });

                      @override
                        State<LiveClassScreen> createState() => _LiveClassScreenState();
                        }

                        class _LiveClassScreenState extends State<LiveClassScreen> {
                          RTCVideoRenderer _localRenderer = RTCVideoRenderer();
                            RTCVideoRenderer _remoteRenderer = RTCVideoRenderer();
                              MediaStream? _localStream;
                                bool _localUserJoined = false;
                                  bool _isMuted = false;
                                    bool _isVideoOff = false;
                                      bool _hasRemoteUser = false;

                                        @override
                                          void initState() {
                                              super.initState();
                                                  _initRenderers();
                                                      _initWebRTC();
                                                        }

                                                          Future<void> _initRenderers() async {
                                                              await _localRenderer.initialize();
                                                                  await _remoteRenderer.initialize();
                                                                    }

                                                                      Future<void> _initWebRTC() async {
                                                                          await [Permission.microphone, Permission.camera].request();

                                                                              final Map<String, dynamic> mediaConstraints = {
                                                                                    'audio': true,
                                                                                          'video': {
                                                                                                  'mandatory': {
                                                                                                            'minWidth': '640', 
                                                                                                                      'minHeight': '480',
                                                                                                                                'minFrameRate': '30',
                                                                                                                                        },
                                                                                                                                                'facingMode': 'user',
                                                                                                                                                        'optional': [],
                                                                                                                                                              }
                                                                                                                                                                  };

                                                                                                                                                                      try {
                                                                                                                                                                            MediaStream stream = await navigator.mediaDevices.getUserMedia(mediaConstraints);
                                                                                                                                                                                  _localStream = stream;
                                                                                                                                                                                        _localRenderer.srcObject = _localStream;
                                                                                                                                                                                              
                                                                                                                                                                                                    setState(() {
                                                                                                                                                                                                            _localUserJoined = true;
                                                                                                                                                                                                                  });
                                                                                                                                                                                                                      } catch (e) {
                                                                                                                                                                                                                            debugPrint("Error getting user media: $e");
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                    void _onToggleMute() {
                                                                                                                                                                                                                                        if (_localStream != null) {
                                                                                                                                                                                                                                              setState(() {
                                                                                                                                                                                                                                                      _isMuted = !_isMuted;
                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                  _localStream!.getAudioTracks().forEach((track) {
                                                                                                                                                                                                                                                                          track.enabled = !_isMuted;
                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                        void _onToggleVideo() {
                                                                                                                                                                                                                                                                                            if (_localStream != null) {
                                                                                                                                                                                                                                                                                                  setState(() {
                                                                                                                                                                                                                                                                                                          _isVideoOff = !_isVideoOff;
                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                      _localStream!.getVideoTracks().forEach((track) {
                                                                                                                                                                                                                                                                                                                              track.enabled = !_isVideoOff;
                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                            void _onSwitchCamera() {
                                                                                                                                                                                                                                                                                                                                                if (_localStream != null) {
                                                                                                                                                                                                                                                                                                                                                      _localStream!.getVideoTracks().forEach((track) {
                                                                                                                                                                                                                                                                                                                                                              Helper.switchCamera(track);
                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                            @override
                                                                                                                                                                                                                                                                                                                                                                              void dispose() {
                                                                                                                                                                                                                                                                                                                                                                                  _localRenderer.dispose();
                                                                                                                                                                                                                                                                                                                                                                                      _remoteRenderer.dispose();
                                                                                                                                                                                                                                                                                                                                                                                          _localStream?.dispose();
                                                                                                                                                                                                                                                                                                                                                                                              super.dispose();
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                  @override
                                                                                                                                                                                                                                                                                                                                                                                                    Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                                        return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                                              backgroundColor: Colors.black,
                                                                                                                                                                                                                                                                                                                                                                                                                    body: Stack(
                                                                                                                                                                                                                                                                                                                                                                                                                            children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                      Center(child: _remoteVideo()), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                Align(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            alignment: Alignment.topLeft,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: 120,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    height: 180,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: Center(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: _localUserJoined && !_isVideoOff
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? RTCVideoView(_localRenderer, mirror: true, objectFit: RTCVideoViewObjectFit.RTCVideoViewObjectFitCover)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : Container(color: Colors.grey[900], child: const Icon(Icons.videocam_off, color: Colors.white)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _buildToolbar(), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Widget _remoteVideo() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (_hasRemoteUser) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return RTCVideoView(_remoteRenderer, objectFit: RTCVideoViewObjectFit.RTCVideoViewObjectFitCover);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return const Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'Waiting for other participants...',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style: TextStyle(color: Colors.white),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Widget _buildToolbar() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return Align(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alignment: Alignment.bottomCenter,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: const EdgeInsets.symmetric(vertical: 40),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: Row(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                RawMaterialButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onPressed: _onToggleMute,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            shape: const CircleBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: const EdgeInsets.all(12.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fillColor: _isMuted ? Colors.redAccent : Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: Icon(_isMuted ? Icons.mic_off : Icons.mic, color: _isMuted ? Colors.white : Colors.blueAccent, size: 20.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              RawMaterialButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Navigator.pop(context);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        shape: const CircleBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: const EdgeInsets.all(15.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fillColor: Colors.redAccent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: const Icon(Icons.call_end, color: Colors.white, size: 35.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          RawMaterialButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: _onToggleVideo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      shape: const CircleBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: const EdgeInsets.all(12.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fillColor: _isVideoOff ? Colors.redAccent : Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: Icon(_isVideoOff ? Icons.videocam_off : Icons.videocam, color: _isVideoOff ? Colors.white : Colors.blueAccent, size: 20.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        RawMaterialButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPressed: _onSwitchCamera,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    shape: const CircleBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: const EdgeInsets.all(12.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fillColor: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: const Icon(Icons.switch_camera, color: Colors.blueAccent, size: 20.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        