import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';

class ForgotPasswordScreen extends StatefulWidget {
  const ForgotPasswordScreen({super.key});

    @override
      State<ForgotPasswordScreen> createState() => _ForgotPasswordScreenState();
      }

      class _ForgotPasswordScreenState extends State<ForgotPasswordScreen> {
        final _emailController = TextEditingController();
          final _formKey = GlobalKey<FormState>();
            bool _isLoading = false;

              @override
                void dispose() {
                    _emailController.dispose();
                        super.dispose();
                          }

                            Future<void> _resetPassword() async {
                                if (!_formKey.currentState!.validate()) return;

                                    setState(() {
                                          _isLoading = true;
                                              });

                                                  try {
                                                        await FirebaseAuth.instance.sendPasswordResetEmail(
                                                                email: _emailController.text.trim(),
                                                                      );
                                                                            _showMessage("A password reset link has been sent to your email.");
                                                                                  
                                                                                        Future.delayed(const Duration(seconds: 3), () {
                                                                                                if (mounted) Navigator.pop(context);
                                                                                                      });
                                                                                                          } on FirebaseAuthException catch (e) {
                                                                                                                _showMessage(e.message ?? "An error occurred");
                                                                                                                    } finally {
                                                                                                                          if (mounted) {
                                                                                                                                  setState(() {
                                                                                                                                            _isLoading = false;
                                                                                                                                                    });
                                                                                                                                                          }
                                                                                                                                                              }
                                                                                                                                                                }

                                                                                                                                                                  void _showMessage(String message) {
                                                                                                                                                                      ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                                                                            SnackBar(
                                                                                                                                                                                    content: Text(message),
                                                                                                                                                                                            behavior: SnackBarBehavior.floating,
                                                                                                                                                                                                  ),
                                                                                                                                                                                                      );
                                                                                                                                                                                                        }

                                                                                                                                                                                                          @override
                                                                                                                                                                                                            Widget build(BuildContext context) {
                                                                                                                                                                                                                return Scaffold(
                                                                                                                                                                                                                      appBar: AppBar(title: const Text('Reset Password')),
                                                                                                                                                                                                                            body: Padding(
                                                                                                                                                                                                                                    padding: const EdgeInsets.all(16.0),
                                                                                                                                                                                                                                            child: Form(
                                                                                                                                                                                                                                                      key: _formKey,
                                                                                                                                                                                                                                                                child: Column(
                                                                                                                                                                                                                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                                                                        children: [
                                                                                                                                                                                                                                                                                                      TextFormField(
                                                                                                                                                                                                                                                                                                                      controller: _emailController,
                                                                                                                                                                                                                                                                                                                                      decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                        labelText: 'Email Address',
                                                                                                                                                                                                                                                                                                                                                                          border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                          validator: (value) {
                                                                                                                                                                                                                                                                                                                                                                                                                            if (value == null || value.isEmpty) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                return 'Please enter your registered email address.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _isLoading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? const CircularProgressIndicator()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: _resetPassword,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: const Text('Reset Password'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            