import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import '../../models/teacher_model.dart';
import 'teacher_profile_screen.dart';

class MapScreen extends StatefulWidget {
  const MapScreen({super.key});

    @override
      State<MapScreen> createState() => _MapScreenState();
      }

      class _MapScreenState extends State<MapScreen> {
        GoogleMapController? _mapController; 

          // Dhaka, Bangladesh as default center
            final LatLng _initialCenter = const LatLng(23.8103, 90.4125); 

              // Localized coordinates lookup map since TeacherModel does not contain geo fields
                final Map<String, LatLng> _teacherLocations = {
                    '1': const LatLng(23.8103, 90.4125),
                        '2': const LatLng(23.8125, 90.4147),
                            '3': const LatLng(23.8150, 90.4100),
                              };

                                // Completely synchronized list matching your exact TeacherModel constructor parameters
                                  final List<TeacherModel> teachers = [
                                      TeacherModel(
                                            id: '1', 
                                                  name: 'Mr. Rahim', 
                                                        isOnline: false,
                                                              lastSeen: DateTime.now().subtract(const Duration(hours: 2)),
                                                                    isTyping: false,
                                                                          isVerified: true,
                                                                                hasSpecialBadge: false, 
                                                                                    ),
                                                                                        TeacherModel(
                                                                                              id: '2', 
                                                                                                    name: 'Ms. Karim', 
                                                                                                          isOnline: false,
                                                                                                                lastSeen: DateTime.now().subtract(const Duration(days: 1)),
                                                                                                                      isTyping: false,
                                                                                                                            isVerified: false,
                                                                                                                                  hasSpecialBadge: true,
                                                                                                                                      ),
                                                                                                                                          TeacherModel(
                                                                                                                                                id: '3', 
                                                                                                                                                      name: 'Dr. Anika', 
                                                                                                                                                            isOnline: true,
                                                                                                                                                                  lastSeen: DateTime.now(),
                                                                                                                                                                        isTyping: false,
                                                                                                                                                                              isVerified: true,
                                                                                                                                                                                    hasSpecialBadge: true,
                                                                                                                                                                                        ),
                                                                                                                                                                                          ];

                                                                                                                                                                                            @override
                                                                                                                                                                                              void dispose() {
                                                                                                                                                                                                  _mapController?.dispose(); 
                                                                                                                                                                                                      super.dispose();
                                                                                                                                                                                                        }

                                                                                                                                                                                                          void _onMapCreated(GoogleMapController controller) {
                                                                                                                                                                                                              _mapController = controller;
                                                                                                                                                                                                                  _fitAllMarkers();
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                      void _fitAllMarkers() {
                                                                                                                                                                                                                          if (teachers.isEmpty || _mapController == null) return;
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                              Set<Marker> _buildMarkers() {
                                                                                                                                                                                                                                  return teachers.map((teacher) {
                                                                                                                                                                                                                                        // Fetch coordinates from the local coordinate mapping system via ID
                                                                                                                                                                                                                                              final LatLng position = _teacherLocations[teacher.id] ?? _initialCenter;

                                                                                                                                                                                                                                                    return Marker(
                                                                                                                                                                                                                                                            markerId: MarkerId(teacher.id),
                                                                                                                                                                                                                                                                    position: position,
                                                                                                                                                                                                                                                                            icon: BitmapDescriptor.defaultMarkerWithHue(BitmapDescriptor.hueAzure), 
                                                                                                                                                                                                                                                                                    infoWindow: InfoWindow(
                                                                                                                                                                                                                                                                                              title: teacher.name,
                                                                                                                                                                                                                                                                                                        onTap: () {
                                                                                                                                                                                                                                                                                                                    Navigator.push(
                                                                                                                                                                                                                                                                                                                                  context,
                                                                                                                                                                                                                                                                                                                                                MaterialPageRoute(
                                                                                                                                                                                                                                                                                                                                                                builder: (context) => TeacherProfileScreen(teacherId: teacher.id),
                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                      }).toSet();
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                          @override
                                                                                                                                                                                                                                                                                                                                                                                                                            Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                                                                      appBar: AppBar(
                                                                                                                                                                                                                                                                                                                                                                                                                                              title: const Text('Teacher Map', style: TextStyle(fontWeight: FontWeight.bold)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor: Colors.blue[800],
                                                                                                                                                                                                                                                                                                                                                                                                                                                              foregroundColor: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          body: GoogleMap(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  initialCameraPosition: CameraPosition(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            target: _initialCenter,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      zoom: 14.0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onMapCreated: _onMapCreated,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              markers: _buildMarkers(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          