import 'dart:async';
import 'package:flutter/material.dart';
import 'welcome_screen.dart'; // your next screen

class SplashScreen extends StatefulWidget {
  const SplashScreen({Key? key}) : super(key: key);

    @override
      State<SplashScreen> createState() => _SplashScreenState();
      }

      class _SplashScreenState extends State<SplashScreen>
          with TickerProviderStateMixin {
            late AnimationController _bounceController;
              late Animation<double> _bounceAnimation;

                late AnimationController _glowController;
                  late Animation<double> _glowAnimation;

                    @override
                      void initState() {
                          super.initState();

                              // 1. লোগোটির সুন্দর ইলাস্টিক বাউন্স অ্যানিমেশন
                                  _bounceController =
                                          AnimationController(duration: const Duration(milliseconds: 1200), vsync: this);
                                              _bounceAnimation =
                                                      CurvedAnimation(parent: _bounceController, curve: Curves.elasticOut);

                                                          // 2. সাইড কাটের জন্য গ্লোয়িং/ব্লিংকিং অ্যানিমেশন
                                                              _glowController = AnimationController(
                                                                      duration: const Duration(milliseconds: 1000), vsync: this);
                                                                          _glowAnimation = Tween<double>(begin: 0.3, end: 1.0).animate(
                                                                                CurvedAnimation(parent: _glowController, curve: Curves.easeInOut),
                                                                                    );

                                                                                        _bounceController.forward();
                                                                                            _glowController.repeat(reverse: true);

                                                                                                // ৩ সেকেন্ড পর পরবর্তী স্ক্রিনে যাওয়ার প্রিমিয়াম ট্রানজিশন
                                                                                                    Timer(const Duration(seconds: 3), () {
                                                                                                          if (mounted) {
                                                                                                                  Navigator.pushReplacement(
                                                                                                                            context,
                                                                                                                                      PageRouteBuilder(
                                                                                                                                                  pageBuilder: (context, animation, secondaryAnimation) => const WelcomeScreen(),
                                                                                                                                                              transitionsBuilder: (context, animation, secondaryAnimation, child) {
                                                                                                                                                                            // এখানে একটি স্মুথ ফেড ট্রানজিশন ব্যবহার করা হয়েছে যা দেখতে খুবই লাক্সারিয়াস লাগে
                                                                                                                                                                                          return FadeTransition(
                                                                                                                                                                                                          opacity: animation,
                                                                                                                                                                                                                          child: child,
                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                transitionDuration: const Duration(milliseconds: 800), // ট্রানজিশনটি ৮০০ মিলিমেকন্ড ধরে স্মুথলি হবে
                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                @override
                                                                                                                                                                                                                                                                                                  void dispose() {
                                                                                                                                                                                                                                                                                                      _bounceController.dispose();
                                                                                                                                                                                                                                                                                                          _glowController.dispose();
                                                                                                                                                                                                                                                                                                              super.dispose();
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                  @override
                                                                                                                                                                                                                                                                                                                    Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                        return Scaffold(
                                                                                                                                                                                                                                                                                                                              backgroundColor: Colors.white,
                                                                                                                                                                                                                                                                                                                                    body: Center(
                                                                                                                                                                                                                                                                                                                                            child: ScaleTransition(
                                                                                                                                                                                                                                                                                                                                                      scale: _bounceAnimation,
                                                                                                                                                                                                                                                                                                                                                                child: Stack(
                                                                                                                                                                                                                                                                                                                                                                            alignment: Alignment.center,
                                                                                                                                                                                                                                                                                                                                                                                        children: [
                                                                                                                                                                                                                                                                                                                                                                                                      Image.asset(
                                                                                                                                                                                                                                                                                                                                                                                                                      'assets/logo.png', // আপনার লোগোর পাথ
                                                                                                                                                                                                                                                                                                                                                                                                                                      height: 180,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Positioned(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  top: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  right: 55,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: FadeTransition(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    opacity: _glowAnimation,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              height: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  decoration: BoxDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: Border.all(color: Colors.black),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    shape: BoxShape.circle,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          boxShadow: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  BoxShadow(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: Colors.white.withOpacity(0.8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      blurRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                spreadRadius: 3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            