import 'package:flutter/material.dart';
import '../main.dart'; 

class WelcomeScreen extends StatefulWidget {
  const WelcomeScreen({super.key});

    @override
      State<WelcomeScreen> createState() => _WelcomeScreenState();
      }

      class _WelcomeScreenState extends State<WelcomeScreen> with SingleTickerProviderStateMixin {
        late AnimationController _controller;
          late Animation<double> _animation;

            @override
              void initState() {
                  super.initState();
                      _controller = AnimationController(
                            vsync: this,
                                  duration: const Duration(seconds: 2),
                                      );
                                          _animation = CurvedAnimation(parent: _controller, curve: Curves.easeIn);

                                              _controller.forward();
                                                }

                                                  @override
                                                    void dispose() {
                                                        _controller.dispose();
                                                            super.dispose();
                                                              }

                                                                void _navigateToNextScreen() {
                                                                    ScaffoldMessenger.of(context).showSnackBar(
                                                                          const SnackBar(content: Text('Proceeding to next screen...')),
                                                                              );

                                                                                  Future.delayed(const Duration(seconds: 1), () {
                                                                                        Navigator.pushReplacement(
                                                                                                context,
                                                                                                        MaterialPageRoute(builder: (_) => const FindYourBestTeacherTodayApp()), 
                                                                                                              );
                                                                                                                  });
                                                                                                                    }

                                                                                                                      @override
                                                                                                                        Widget build(BuildContext context) {
                                                                                                                            return Scaffold(
                                                                                                                                  body: Container(
                                                                                                                                          width: double.infinity,
                                                                                                                                                  decoration: const BoxDecoration(
                                                                                                                                                            gradient: LinearGradient(
                                                                                                                                                                        colors: [Color(0xFFE0F7FA), Color(0xFFFFFFFF)], 
                                                                                                                                                                                    begin: Alignment.topCenter,
                                                                                                                                                                                                end: Alignment.bottomCenter,
                                                                                                                                                                                                          ),
                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                          child: FadeTransition(
                                                                                                                                                                                                                                    opacity: _animation,
                                                                                                                                                                                                                                              child: Column(
                                                                                                                                                                                                                                                          mainAxisAlignment: MainAxisAlignment.start,
                                                                                                                                                                                                                                                                      children: [
                                                                                                                                                                                                                                                                                    const SizedBox(height: 60),
                                                                                                                                                                                                                                                                                                  const Text(
                                                                                                                                                                                                                                                                                                                  'Welcome',
                                                                                                                                                                                                                                                                                                                                  style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                    fontSize: 36,
                                                                                                                                                                                                                                                                                                                                                                      fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                        color: Colors.deepPurple,
                                                                                                                                                                                                                                                                                                                                                                                                          letterSpacing: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 30),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Find Your Best Teacher Today',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: Colors.deepPurpleAccent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            letterSpacing: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: EdgeInsets.symmetric(horizontal: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Don't wait for tomorrow — discover your best teacher today!",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontStyle: FontStyle.italic,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: Colors.black87,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 40),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onPressed: _navigateToNextScreen,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: ElevatedButton.styleFrom(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor: Colors.deepPurple,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 15),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          shape: RoundedRectangleBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: BorderRadius.circular(30),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: const Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'Get Started',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: TextStyle(fontSize: 18, color: Colors.white),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const Spacer(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: EdgeInsets.only(bottom: 16.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Created by Md Imran Mondal',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontStyle: FontStyle.italic,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: Colors.grey,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        